# Generated by Django 5.0 on 2024-03-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetables_name', models.TextField(unique=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Ladies_clothes',
            new_name='fruits',
        ),
        migrations.RemoveField(
            model_name='cartentrties',
            name='Gentsclothes',
        ),
        migrations.RenameField(
            model_name='cartentrties',
            old_name='Lediesclothes',
            new_name='fruit',
        ),
        migrations.RenameField(
            model_name='fruits',
            old_name='L_Cloth_name',
            new_name='fruit_name',
        ),
        migrations.AddField(
            model_name='cartentrties',
            name='fruitandveg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothstoreapp.vegetables'),
        ),
        migrations.DeleteModel(
            name='Gents_clothes',
        ),
    ]
