# Generated by Django 5.0 on 2024-03-06 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothstoreapp', '0002_vegetables_rename_ladies_clothes_fruits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vegetables',
            new_name='Ladiesclothes',
        ),
        migrations.RenameModel(
            old_name='fruits',
            new_name='Mensclothes',
        ),
        migrations.CreateModel(
            name='Orderedd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothstoreapp.mensclothes')),
                ('fruitandveg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clothstoreapp.ladiesclothes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
