# Generated by Django 5.0 on 2024-03-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothstoreapp', '0004_rename_vegetables_name_ladiesclothes_ladies_cloth_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensclothes',
            old_name='Men_cloth_name',
            new_name='mensclothes',
        ),
    ]
