# Generated by Django 5.0 on 2024-03-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothstoreapp', '0005_rename_men_cloth_name_mensclothes_mensclothes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartentrties',
            old_name='fruit',
            new_name='dres',
        ),
        migrations.RenameField(
            model_name='cartentrties',
            old_name='fruitandveg',
            new_name='shirtandpant',
        ),
        migrations.RenameField(
            model_name='orderedd',
            old_name='fruit',
            new_name='clothswhole',
        ),
        migrations.RenameField(
            model_name='orderedd',
            old_name='fruitandveg',
            new_name='dresss',
        ),
    ]
