# Generated by Django 5.0 on 2024-03-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothstoreapp', '0008_rename_men_dress_cartentrties_mens_dress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartentrties',
            old_name='mens_dress',
            new_name='fruit',
        ),
        migrations.RenameField(
            model_name='cartentrties',
            old_name='womens_dress',
            new_name='fruitandveg',
        ),
        migrations.RenameField(
            model_name='orderedd',
            old_name='clothswhole',
            new_name='fruit',
        ),
        migrations.RenameField(
            model_name='orderedd',
            old_name='dresss',
            new_name='fruitandveg',
        ),
    ]
