# Generated by Django 5.0 on 2024-03-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothstoreapp', '0009_rename_mens_dress_cartentrties_fruit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartentrties',
            old_name='fruitandveg',
            new_name='ladies_cloth_cart',
        ),
        migrations.RenameField(
            model_name='cartentrties',
            old_name='fruit',
            new_name='men_cloth_cart',
        ),
    ]
