# Generated by Django 5.0 on 2024-03-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothstoreapp', '0010_rename_fruitandveg_cartentrties_ladies_cloth_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedd',
            old_name='fruitandveg',
            new_name='ladies_cloth_cart',
        ),
        migrations.RenameField(
            model_name='orderedd',
            old_name='fruit',
            new_name='men_cloth_cart',
        ),
    ]
